src/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bio', views.bio, name='bio'),
    url(r'^projets', views.projets, name='projets'),
    url(r'^competences', views.competences, name='competences'),
    url(r'^experiences', views.experiences, name='experiences'),
    url(r'^informatique', views.informatique, name='informatique'),
    url(r'^autre', views.autre, name='autre'),

    url(r'^post/(?P<id>[0-9]+)$', views.show, name='show'),

]

src/mysite/urls.py
from django.conf import settings
from django.conf.urls import re_path, url
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

handler404 = 'mysite.views.handler404'
handler500 = 'mysite.views.handler500'

urlpatterns = [
    re_path('^$', views.home, name='home'),
    re_path('^about/', views.about, name='about'),
    re_path('^contact/', views.contact, name='contact'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()


admin.site.site_header = "Sabrigan Admin"
admin.site.site_title = "Portail Administration Sabrigan"
admin.site.index_title = "Bienvenue sur le site admin de MR Sabrigan"

src/blog/models.py
from django.db import models



class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        verbose_name_plural = "PostS"



class Post(Timestamp):
    title = models.CharField(max_length=255)
    body = models.TextField()
    test = models.BooleanField(default=False)
    date_de_debut = models.DateTimeField(auto_now=False)
    date_de_fin = models.DateTimeField(auto_now_add=False)
    url_test = models.URLField(default="www.pierre-dauphin.hopto.org")
    image = models.ImageField(default="{%static img/fond1.jpg %}")


    def __str__(self):
        return self.title

src/mysite/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'blog/pages/bio.html')

def about(request):
    return render(request, 'pages/about.html')


def contact(request):
    return render(request, 'pages/contact.html')


def handler404(request, exception):
    return render(request, 'errors/Erreur404.html')


def handler500(request):
    return render(request, 'errors/Erreur500.html')

src/blog/templates/blog/index.html
{% extends 'blog/layout/base.html' %}

{% block title %}Blog{% endblock %}

{% block body %}
<h1>My index ({{posts|length}} articles)</h1>

{% for post in posts %}
<article>
    <h2 class="title">
        #{{post.id}} - {{post.title|upper}}
    </h2>
    <p class="content">{{post.body|truncatewords:3}}</p>
    <p class="time">
        <time datetime="{{post.created_at|date:'Y-m-d'}}">Posted {{post.created_at|timesince}} ago</time>
    </p>
    <p><a href="{% url 'blog:show' post.id %}">Lire la suite</a></p>
</article>

{% empty %}
<p> Déso pas d'article</p>
{% endfor %}

{% endblock %}

src/blog/templates/blog/layout/_footer.html
<footer class="footer text-center">
    <p>&copy; Copyright Monsite {% now 'Y' %} All right reserved</p>
</footer>

src/blog/templates/blog/layout/_nav.html
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-pills">
                    <li><a href="{% url  'blog:bio' %}">Home</a></li>
                    <li><a href="{% url  'blog:projets' %}">Projet</a></li>
                    <li><a href="{% url  'blog:competences'%}">Compétences</a></li>
                    <li><a href="{% url  'blog:experiences'%}">Expériences</a></li>
                    <li><a href="{% url  'blog:informatique'%}">Informatique</a></li>
                    <li><a href="{% url  'blog:autre'%}">Autre</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

src/blog/templates/blog/layout/base.html
{% extends 'layout/base.html' %}

{% load static from staticfiles %}

{% block stylesheets %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script type="text/javascript"
	src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript"
	src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<link href="{%static 'css/style1.css'%}" rel="stylesheet" type="text/css">
<link href="{%static 'css/style2.css'%}" rel="stylesheet" type="text/css">
<link href="{%static 'css/styles.css'%}" rel="stylesheet" type="text/css">
{%endblock%}


{% block content %}

{%block body%}{%endblock%}

{% block javascripts %}{%endblock%}

{% include 'blog/layout/_footer.html' %}

{%endblock%}

src/blog/templates/blog/pages/bio.html
{% extends 'blog/layout/base.html' %}
{% load static from staticfiles %}

{% block title %} Bio{% endblock %}
{% block content %}
<div>
	<link title="timeline-styles" rel="stylesheet" href="{%static 'timeline3/css/timeline.css'%}">
    <script src="{%static 'timeline3/js/timeline.js'%}"></script>
    <div id='timeline-embed' style="width: 100%; height: 600px">
        <script type="text/javascript">
            var timeline_json = "{%static 'bio.json'%}";
            var additionalOptions = {
             start_at_end: true,
              default_bg_color: {r:0, g:0, b:0},
              timenav_height: 150
            }
            timeline = new TL.Timeline('timeline-embed',
                timeline_json,
                additionalOptions);
        </script>
    </div>
</div>

{% include 'blog/layout/_nav.html' %}


{% block body %}
<article>
    <!--<h1 class="title">#{{post.id}} - {{post.title}}</h1>--!>
    <!--<p class="content">{{post.body}}</p>--!>
    <div class="section">
        <div class="container">
            <h1>Petite biographie</h1>
            <div class="row">
                <div class="col-md-4">
                    <p>Né le 8 mai 1984 à Bordeaux, j'ai grandi dans une famille de
                        5 personnes. Mon père, professeur, et ma mère, infirmière, m'ont
                        très vite poussé à faire de la musique. D'abord un peu de violon
                        mais ayant les oreilles sensibles et mon frère et ma soeur en bas
                        age, mes parents ont vite accepté que j'abandonne pour un autre
                        instrument, la clarinette, moins crispant lors de mauvaises notes.</p>
                    <p>
                        J'ai également lors de mon enfance découvert un certain nombre de
                        domaines comme l'astronomie, l'informatique, la photographie et
                        son developpement. Mon frere et ma soeur (jumeaux) ont eux aussi
                        bénéficiés de cet apport de la musique, ma soeur en ayant même
                        fait une partie de son travail en tant que luthière. Vous
                        trouverez sur ces points plus de détails dans la partie <a
                            href="autre.html">Autre</a>
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        Ayant un attrait pour la recherche et plus précisement
                        l'astrophysique au depart j'ai commencé mes études supérieures à
                        l'université Bordeaux 1 et ai effectué une licence en physique
                        fondamentale. En 2007, j'ai déménagé à Paris afin de continuer en
                        effectuant un master mais devant travailler en même temps j'ai
                        effectué un changement dans mon parcours en intégrant <a
                            href="https://www.cefipa.com">l'école d'ingénieur du CESI</a>
                        directement en deuxième année dans le parcours en alternance.
                    </p>
                    <p>
                        Apres deux ans en alternance chez PSA Peugeot Citroën
                        d'abord à Poissy en production puis en recherche et developpement,
                        j'ai effectué une thèse à Créteil pendant laquelle j'ai découvert
                        ma passion pour la programmation. J'ai développé en IDL (un
                        langage spécifique à la télédétection) un algorithme permettant
                        d'optimiser le choix des canaux spectraux de satellite pour la
                        télédétection de l'ozone troposphérique, polluant atmosphérique.
                        Parallèlement à cet algorithme j'ai mis en place ce que l'on appel
                        OSSE (Observing Systeme Simulation Experiment) permettant de
                        comparer les performances d'un système d'observation.
                    </p>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <p>
                        Arrivé jusque là, j'ai postulé tant sur des postes de
                        recherches dans le publique que d'ingénieur dans le privé. Mes
                        diplomes ne reflétant pas mes compétences, je me suis donc tourné
                        vers la formation proposer par GTM-Ingénierie afin d'obtenir les
                        compétences nécessaires pour devenir Developpeur Java JEE
                    </p>
                    <p>
                        Ce retour à l'informatique appliqué fut le fruit d'une
                        reflexion pendant l'année de professorat que j'ai effectué dans un
                        lycée professionnel. Durant cette année j'ai été en charge des
                        cours de mathématique et physique chimie de classes allant du CAP
                        au terminal de bac professionnel.
                    </p>
                    <p>
                        Suite donc à la formation en Java JEE faite chez GTM-Ingénierie,
                        formation tres acces pratique et peu théorique, j'ai intégré une
                        entreprise de presation, <a href="https://www.sodifrance.fr">
                        Sodifrance </a>. Cherchant d'abord à renforcer mes compétences
                        informatique, j'ai été envoyé chez <a
                            href="https://www.fr.adp.com"> ADP-GSI </a> en tant que
                        développeur. Durant les quelques mois où j'ai pu contribuer a
                        cette entreprise j'ai été en fin de compte mis sur un poste de
                        relation client. Le sujet de la gestion RH n'etait deja pas mon
                        objectif de carrière donc j'ai demandé en interne un changement de
                        poste. Parallèlement à cela j'ai cherché dans mes contacts et
                        trouver une personnes travaillant pour une autre entreprise de
                        service numérique. Nous avons echangé et m'a été proposé un poste
                        tres interessant.
                    </p>
                </div>
                <div class="col-md-4">
                    <p>
                        J'ai donc reussi à trouver un poste qui corresponde à mon plan de
                        carrière. L'entreprise Silicom m'a donc envoyé en prestation de
                        service dans une des nouvelles equipes de cybersécurité de
                        l'entreprise <a href="https://airbus-cyber-security.com/fr/">
                        Airbus Defense and Space</a>. Durant les mois de juin à aout alors
                        que les équipes sont en vacances je me suis autoformé sur les
                        sujet de cybersécurité et machine learning afin de repondre à un
                        appel d'offre gouvernemental. Nous avons avec notre équipe
                        developpé un systeme de detection des anomalie de comportement
                        dans un systeme d'information. Apres le test de differentes
                        méthode nous avons opter pour un algorithme developper par un
                        groupe issu de HP qui est de type isolation forest. Cette mission
                        terminée en janvier, Silicom a tenté de caser mon profil sur des
                        missions un peu plus éloigné de mes compétences malgré mes
                        avertissements. J'ai donc suggérer qu'il me permette de me former
                        sur les datasciences qui est un secteur en pleine explosion et que
                        silicom n'avait pas du tout investi. Nous nous sommes donc séparé.
                    </p>
                    <p>
                        Heureusement a peine deux mois apres cette séparation, Pole emploi
                        m'a proposé une formation en datasciences, avec <a
                            href="http://www.ortformation.com"> ORT </a> et <a
                            href="https://datascientest.com"> Datascientest </a>. Nous avons
                        étudié donc la data visualisation, les regressions,
                        classifications, NLP, computation vision, reseaux de neurones.
                    </p>
                    <p>Parallèlement a mon parcours professionnel je suis depuis
                        avril 2018 au conseil d'administration d'une des grandes
                        associations de lutte contre le sida en tant que cosecretaire
                        générale. Cela m'a permis de developper mes compétences de
                        gestion.
                    </p>
                </div>
            </div>
            <blockquote>
                <p>Petit résumé</p>
                <footer>Naissance à Bordeaux en 1984</footer>
                <footer>Père professeur, mère infirmière</footer>
                <footer>Déménagement seul en 2007 pour vivre à Paris</footer>
                <footer>Persévérence dans mes études jusqu'à obtenir le
                    status de docteur ES sciences en "Physique de l'atmosphère et
                    chimie de la pollution"</footer>
                <footer>Pas d'hesitation à se remettre en question pour
                    arriver à mes objectifs</footer>
                <footer>Professorat</footer>
                <footer>Intégration de la formation GTM-Ingenierie en Java
                    JEE afin de trouver un poste dans le domaine qui m'interesse
                    réellement maintenant</footer>
                <footer>ADP GSI</footer>
                <footer>Airbus Defense and Space</footer>
                <footer>Formation datascientist via la plateforme
                    Datascientest</footer>
                <footer>Responsabilité associative au sein d'une
                    association de lutte contre le VIH</footer>
            </blockquote>
        </div>
    </div>


</article>

<!--<p><a href="{% url 'blog:index' %}">revenir à l'index</a></p>--!>

{% endblock %}
{% include 'blog/layout/_footer.html' %}

{% endblock %}

src/blog/templates/blog/pages/competences.html
{% extends 'blog/layout/base.html' %}

{% load static %}

{% block title %} Mes Compétences {% endblock %}--!>
{% block content %}
<div>
	<link title="timeline-styles" rel="stylesheet" href="{%static 'timeline3/css/timeline.css'%}">
    <script src="{%static 'timeline3/js/timeline.js'%}"></script>
    <div id='timeline-embed' style="width: 100%; height: 600px">
        <script type="text/javascript">
            var timeline_json = "{%static 'competence.json'%}";
            var additionalOptions = {
             start_at_end: true,
              default_bg_color: {r:0, g:0, b:0},
              timenav_height: 150
            }
            timeline = new TL.Timeline('timeline-embed',
                timeline_json,
                additionalOptions);
        </script>
    </div>
</div>

{% include 'blog/layout/_nav.html' %}

{% block body %}
<article>
    <!--<h1 class="title">#{{post.id}} - {{post.title}}</h1>--!>
    <!--<p class="content">{{post.body}}</p>--!>
<div class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<p class="text-center">
						Domaine de compétence : <br> <br>
					<ul>
						<li>Management d'équipe (dans l'associatif et egalement une expérience comme SCRUM Master)</li>
						<li>Datascience, Machine Learning et Intelligence Artificielle</li>
						<li>Physique Fondamentale (Electromagnétisme, Mecanique)</li>
						<li>Télédetection:<br> Au travers de ma thèse j'ai pu
							pendant 3ans me concentrer sur ce domaine en particulier les
							sattelites defilants LEO ainsi que l'analyse spectroscopique de
							l'atmosphère et les notions mathématiques d'inversion permettant la
							comprehension de ces analyses spectroscopiques
						</li>
						<li>Programmation, Simulation: <br>Depuis le debut de
							mes contacts avec le monde professionnel (lors de stage en
							laboratoire ou pendant mon alternance) j'ai été plongé dans la
							programmation qu'elle soit ou non orienté objet. Ces
							programmations étaient autant lié à la simulation de phénomène
							physique que de l'analyse de donnée
						</li>
						<li>Mathématiques appliquées</li>
						<li>Gestion d'équipe et de projet:<br> Lors de ma
							dernière année en alternance chez PSA j'ai eu en charge un projet
							entreprise (j'avais en charge deux personnes et le
							retroplanning).
						</li>
						<li>Datasciences et Machine Learning:<br> Lors de ma
							dernière mission au sein de Airbus, j'ai créé avec mon equipe un programme de detection d'UEBA (User Entity Behaviour Anomaly).
						</li>
					</ul>
				</div>
				<!--<div class="col-md-4">-->
					<!--<img-->
						<!--src="https://ununsplash.imgix.net/photo-1423753623104-718aaace6772?w=1024&amp;q=50&amp;fm=jpg&amp;s=1ffa61419561b5c796bca3158e7c704c"-->
						<!--class="img-responsive">-->
				<!--</div>-->
			</div>
		</div>
	</div>
</article>

<!--<p><a href="{% url 'blog:index' %}">revenir à l'index</a></p>--!>

{% endblock %}
{% endblock %}

src/blog/templates/blog/pages/experiences.html
{% extends 'blog/layout/base.html' %}

{% load static %}

{% block title %} Mes Expériences {% endblock %}--!>
{% block content %}
<div>
	<link title="timeline-styles" rel="stylesheet" href="{%static 'timeline3/css/timeline.css'%}">
    <script src="{%static 'timeline3/js/timeline.js'%}"></script>
    <div id='timeline-embed' style="width: 100%; height: 600px">
        <script type="text/javascript">
            var timeline_json = "{%static 'experience.json'%}";
            var additionalOptions = {
             start_at_end: true,
              default_bg_color: {r:0, g:0, b:0},
              timenav_height: 150
            }
            timeline = new TL.Timeline('timeline-embed',
                timeline_json,
                additionalOptions);
        </script>
    </div>
</div>

{% include 'blog/layout/_nav.html' %}

{% block body %}
<article>
    <!--<h1 class="title">#{{post.id}} - {{post.title}}</h1>--!>
    <!--<p class="content">{{post.body}}</p>--!>
<div class="section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p class="text-center">
						Mes experiences professionnelles:<br> <br>
					<div>
						<p class="text-center">
							juin 2017-mars 2018:Ingénieur d'études et développement
							Cybersécurité/Machine Learning<br>
						<p>
							En prestation à nouveaux chez <a href="https://www.airbus.com">Airbus
								Defense and Space</a> j'ai mis en pratique de façon plus profonde
							mes connaissances en machine learning, intelligence artificielle
							et traitement de donnée complexe pour un projet interne.<br>
							<br>
						<p class="text-center">
							nov. 2016-juin 2017:Ingénieur clientèle<br>
						<p>
							En prestation pour <a href="http://www.sodifrance.fr">Sodifrance</a>
							chez ADP/GSI, j'ai été en charge des relations entre les clients
							d'une application de SIRH et les developpeurs situé en dehors du
							territoire français.<br> <br>
						<p class="text-center">
						<p class="text-center">
							oct. 2015-avr. 2016: Professeur contractuel de Maths sciences
							physique en Lycée Professionel<br>
						<p>
							En remplacement en tant que professeur de Mathématiques et
							sciences physique au<a
								href="https://www.ac-paris.fr/serail/jcms/s6_204421/ee-lyc-vauquelin-portail">lycée
								professionnel Louis Nicolas Vauquelin</a>. J'avais en charge avec
							une dominance en sciences physiques des classes de tout niveaux
							(2nd 1ère Tle bac pro et CAP). Cette expérience m'a permis de
							comprendre un certain nombre de choses en pédagogie et en
							dynamique de groupe. La conduite d'une classe s'apparente
							beaucoup a une conduite de projet, le chef de projet comme le
							chef de classe doit pouvoir faire face aux difficultés des élèves
							dans la discipline et dans le travail de groupe.<br> <br>
							Mais cela m'a permis d'être certain que la carrière d'enseignant
							dans le secondaire n'etait pas pour moi, malgré le bon contact
							avec les élèves. En effet, c'est moins le fait d'être en charge
							d'enfant que le fait de ne pas pouvoir créer mes propres sujets
							de reflexions qui m'a convaincu que je n'étais pas fait pour être
							enseignant dans le secondaire. <br> <br>
						<p class="text-center">
							janv. 2011-dec. 2013:Docteur en physique de l'atmosphère et
							chimie de la pollution <br>
						<p>
							Afin de valoriser mon diplôme d'ingénieur généraliste, j'ai
							réalisé une thèse au <a href="http://www.lisa.univ-paris12.fr/fr">LISA</a>
							dans l'équipe Pollution du laboratoire se situant à l'université
							Paris Est Créteil. Lors de ces trois ans j'ai pu d'une part
							apprendre par la recherche à presenter des résultats en publique
							sur des posters mais aussi en presentation orale. De plus J'ai
							acquis par l'experience des compétences en architecture logiciel
							dans mon projet d'algorithme d'aide à la décision dans la
							sélection de fenêtre spectrale pour la surveillance de l'ozone
							tropospherique. La seconde partie de ma thèse s'est concentrer
							sur l'analyse de données et leur intercomparaison afin de
							determiner les valeurs ajoutées de satellites selectionnées.
							J'étais pour ma part en charge de l'analyse finale quand mon
							collègue Pasquale Selitto, lui, se chargeait de la simulation de
							ces satellite et de la simulation de leurs observation. <br>
							<br>
						<p class="text-center">
							juill. 2008- oct 2010: Ingénieur production/R-D en Alternance
							chez PSA <br>
						<p>
							Apres une année à Paris les conditions de vie où j'étais m'ont
							contraintes à bifurquer vers un parcours d'ingénieur en
							alternance. J'ai donc intégré l'ecole d'ingénieur du <a
								href="http://www.cesi.fr">CESI</a> directement la 2eme année.
							Lors de cette deuxième année, j'ai travaillé en tant
							qui'ingénieur de production à l'usine de Poissy de PSA- Peugeot
							Citroen, mettant en oeuvre la methode Hoshin (dont j'ai aussi
							fait le sujet de mon premier mémoire). Cette methode est une
							methode importée du japon visant à optimiser les lignes de
							production en observant toutes les etapes et toutes les actions
							lors de ces étapes de la ligne de production.<br> Afin de
							valider ce diplome, j'ai effectué un Stage au Queen Mary
							University London pendant deux mois, à londres, experimentant le
							plongeon dans une nouvelle culture et me permettant du même coup
							de bien maitriser la langue anglaise.<br> <br> Après ce
							stage j'ai ensuite intégré le service de Recherche et
							Developpement de PSA, et j'ai conduit un petit projet interne sur
							un logiciel de simulation de deformation des structures lors de
							chocs frontaux et latéraux. L'equipe avec qui je travaillais
							voyant mon attrait pour la recherche et le developpement et les
							nouvelles technologies developpées dans l'entreprise m'ont
							conseillé de valoriser mon diplome d'ingenieur par une thèse mais
							la situation économique de l'entreprise m'a obligé à postuler en
							dehors et m'a remis sur la route des études universitaires. <br>
						<p class="text-center">
							<br> juill. 2007- oct 2009: équipier chez quick à Chatelet
						</p>
						<p class="text-center">
							<br> <br> juill. 2006- aout 2006: ASH à l'hopital
							Pellegrin de Bordeaux
						</p>
						<p class="text-center">
							<br> <br>juin. 2006- juill. 2006: Stagiaire de Licence



						<p>stage CENBG durant lequel j'ai eu mon premier contact avec
							la simulation informatique. En effet j'ai durant ce stage de
							licence simuler de façon simplifiée les phenomènes
							électromagnétique d'une étoile à neutron
					</div>
				</div>
			</div>
		</div>
	</div>
</article>

<!--<p><a href="{% url 'blog:index' %}">revenir à l'index</a></p>--!>

{% endblock %}
{% endblock %}

src/blog/templates/blog/pages/informatique.html
{% extends 'blog/layout/base.html' %}

{% load static %}

{% block title %} Informatique {% endblock %}


{% block body %}

{% include 'blog/layout/_nav.html' %}


<article>
<div class="section">
		<div class="container">
			<p class="text-center">Ci-dessous vous pouvez voir une
				auto-évaluation des differents langages de programmation et autres
				concepts liés que j'ai pu tester ou utiliser de façon courante lors
				de mes differentes expériences</p>
			<div class="row">
				<div class="col-md-4">
					<ul>
						<li><progress value="70" max="100">70%</progress>Python</li>
						<li><progress value="70" max="100">70%</progress>Apprentissage supervisé</li>
						<li><progress value="70" max="100">70%</progress>kera</li>
						<li><progress value="70" max="100">70%</progress>seaborn</li>
						<li><progress value="70" max="100">70%</progress>UML</li>
						<li><progress value="80" max="100">80%</progress>Java</li>
						<li><progress value="50" max="100">50%</progress>SQL</li>
						<li><progress value="50" max="100">50%</progress>JUNIT</li>
						<li><progress value="30" max="100">30%</progress>Design Pattern</li>
						<li><progress value="40" max="100">40%</progress>CDI</li>
						<li><progress value="80" max="100">80%</progress>Jsf</li>
					</ul>
				</div>
				<div class="col-md-4">
					<ul>
						<li><progress value="70" max="100">70%</progress>R</li>
						<li><progress value="70" max="100">70%</progress>Deep Learning</li>
						<li><progress value="70" max="100">70%</progress>ggplot2</li>
						<li><progress value="80" max="100">80%</progress>Jsp</li>
						<li><progress value="60" max="100">60%</progress>Maven</li>
						<li><progress value="40" max="100">40%</progress>EJB</li>
						<li><progress value="40" max="100">40%</progress>Web Service</li>
						<li><progress value="40" max="100">40%</progress>Java
							Security</li>
						<li><progress value="70" max="100">70%</progress>Scrum</li>
						<li><progress value="50" max="100">50%</progress>Spring</li>
					</ul>
				</div>
				<div class="col-md-4">
					<ul>
						<li><progress value="70" max="100">70%</progress>panda</li>
						<li><progress value="70" max="100">70%</progress>Django</li>
						<li><progress value="70" max="100">70%</progress>scikit-learn</li>
						<li><progress value="75" max="100">75%</progress>Github</li>
						<li><progress value="60" max="100">60%</progress>Angular JS</li>
						<li><progress value="90" max="100">90%</progress>Fortran</li>
						<li><progress value="80" max="100">80%</progress>IDL</li>
						<li><progress value="60" max="100">60%</progress>MatLab</li>
						<li><progress value="40" max="100">20%</progress>Unity C#</li>
						<li><progress value="40" max="100">40%</progress>Bash</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

</article>

<!--<p><a href="{% url 'blog:index' %}">revenir à l'index</a></p>--!>

{% endblock %}

src/blog/templates/blog/show.html
{% extends 'blog/layout/base.html' %}

{% block title %} Blog | {{post.title}} {% endblock %}

{% block body %}
<article>
    <h1 class="title">#{{post.id}} - {{post.title}}</h1>
    <p class="content">{{post.body}}</p>
</article>

<p><a href="{% url 'blog:index' %}">revenir à l'index</a></p>

{% endblock %}

src/templates/layout/_footer.html
<footer class="footer text-center">
    <p>&copy; Copyright Monsite {% now 'Y' %} All right reserved</p>
</footer>

src/templates/layout/_nav.html
<nav class="navbar">
    <div class="wrapper">
        <a href="{% url 'home' %}" class="navbar-brand">Mon site</a>
        <ul class="navbar-right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
    </div>
</nav>

src/templates/pages/about.html
{% extends 'layout/base.html' %}

{% block title %}About{% endblock %}


{% block content %}

about me

{% endblock %}

src/templates/pages/home.html
{% extends 'layout/base.html' %}

{% block title %}Homepage{% endblock %}

{% load static from staticfiles %}

{% block content %}
<div class="cover-image">
	<div class="col-md-12 text-center">
		<p style="color: white;">BienvenuEs à vous touTEs</p>
		<br> <br>
		<a class="btn btn-lg btn-default" href="{% url 'blog:bio' %}">
			Entrer si vous souhaitez en savoir plus sur moi blabla
		</a>
		<a href="{% url 'blog:bio' %}">
			Entrer 2
		</a>
	</div>
</div>
{% endblock %}